language: python

python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"

install:
    - pip install -r requirements.txt --use-mirror
    - pip install -r requirements_test.txt --use-mirror

script:
    - python setup.py test

after_success:
    - pip install coveralls
    - coveralls

branches:
  only:
    - master

notifications:
    email: false
